-- DML

-- Inserindo dados na minha tabela empresa

select * from empresa;

INSERT INTO empresa (
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura
                    )
                    VALUES (
                        "Rafael César da Rocha",
                        "219.877.286-88",
                        "28.618.760-7",
                        "21/03/1991",
                        "Masculino",
                        "Eduarda Mirella",
                        "Theo Benjamin da Rocha",
                        "rafael-darocha83@arablock.com.br",
                        "64082-596",
                        "Quadra 64",
                        "300",
                        "Renascença",
                        "Teresina",
                        "PI",
                        "(86) 3688-0918",
                        "Evelyn e Luan Eletrônica Ltda",
                        "17.092.997/0001-50",
                        "563.730.190.215",
                        "16/08/2017"
                    );

INSERT INTO empresa (
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura
                    )
                    VALUES (
                        "Gabrielly Fernanda Sophia Teixeira",
                        "506.362.278-04",
                        "39.513.008-6",
                        "01/04/1979",
                        "Feminino",
                        "Vitória Cláudia Lívia",
                        "Guilherme Breno Isaac Teixeira",
                        "gabrielly-teixeira90@telefonica.com",
                        "46550-972",
                        "Rua Principal, s/n",
                        "667",
                        "Varzinha",
                        "Rio do Pires",
                        "BA",
                        "(77) 3842-6630",
                        "Nair e Sônia Joalheria Ltda",
                        "84.778.557/0001-48",
                        "551.015.533.738",
                        "04/03/2017"
                    );

INSERT INTO empresa (
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura
                    )
                    VALUES (
                        "Giovana Andrea Maria Brito",
                        "254.706.782-02",
                        "45.148.533-6",
                        "24/04/1951",
                        "Feminino",
                        "Sabrina Tânia",
                        "Theo Isaac Renato Brito",
                        "giovana.andrea.brito@origamieventos.com.br",
                        "64211-060",
                        "Quadra G",
                        "833",
                        "Dirceu Arcoverde",
                        "Parnaíba",
                        "PI",
                        "(86) 2564-8894",
                        "Débora e Josefa Contábil Ltda",
                        "70.822.086/0001-13",
                        "276.324.927.451",
                        "03/12/2017"
                    );

INSERT INTO empresa (
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura
                    )
                    VALUES (
                        "Isabel Valentina da Luz",
                        "699.533.384-50",
                        "50.014.472-2",
                        "01/05/2001",
                        "Feminino",
                        "Olivia Vera Bianca",
                        "Leandro João da Luz",
                        "isabel_valentina_daluz@br.loreal.com",
                        "29114-330",
                        "Avenida Graça Aranha",
                        "653",
                        "São Torquato",
                        "Vila Velha",
                        "ES",
                        "(27) 3967-1653",
                        "Olivia e Nathan Publicidade e Propaganda Ltda",
                        "52.579.666/0001-40",
                        "727.649.184.447",
                        "04/01/2017"
                    );

INSERT INTO empresa (
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura
                    )
                    VALUES (
                        "Malu Sueli Barbosa",
                        "003.771.464-39",
                        "21.494.514-5",
                        "19/05/1954",
                        "Feminino",
                        "Clara Catarina",
                        "Igor Juan Barbosa",
                        "malu-barbosa98@allianceconsultoria.com.br",
                        "69099-862",
                        "Rua Imaculada Conceição",
                        "598",
                        "Jorge Teixeira",
                        "Manaus",
                        "AM",
                        "(92) 2883-3520",
                        "Giovana e Rosângela Filmagens ME",
                        "59.676.639/0001-34",
                        "951.117.669.109",
                        "22/11/2017"
                    );
                    
-- Aqui estou inserindo uma empresa que possui uma conta bancária assim fazendo a relação de tabelas
INSERT INTO empresa (
                        id,
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura,
                        conta_bancaria_empresa_id
                    )
                    VALUES (
                        'id',
                        'nome',
                        'cpf',
                        'rg',
                        'data_nascimento',
                        'sexo',
                        'nome_mae',
                        'nome_pai',
                        'email',
                        'cep',
                        'endereco',
                        'numero',
                        'bairro',
                        'cidade',
                        'estado',
                        'telefone',
                        'razao_social',
                        'cnpj',
                        'inscricao_estadual',
                        'data_de_abertura',
                        'conta_bancaria_empresa_id'
                    );

-- Aqui estou inserindo uma empresa que possui uma conta bancária assim fazendo a relação de tabelas
INSERT INTO empresa (
                        id,
                        nome,
                        cpf,
                        rg,
                        data_nascimento,
                        sexo,
                        nome_mae,
                        nome_pai,
                        email,
                        cep,
                        endereco,
                        numero,
                        bairro,
                        cidade,
                        estado,
                        telefone,
                        razao_social,
                        cnpj,
                        inscricao_estadual,
                        data_de_abertura,
                        conta_bancaria_empresa_id
                    )
                    VALUES (
                        'id',
                        'nome',
                        'cpf',
                        'rg',
                        'data_nascimento',
                        'sexo',
                        'nome_mae',
                        'nome_pai',
                        'email',
                        'cep',
                        'endereco',
                        'numero',
                        'bairro',
                        'cidade',
                        'estado',
                        'telefone',
                        'razao_social',
                        'cnpj',
                        'inscricao_estadual',
                        'data_de_abertura',
                        'conta_bancaria_empresa_id'
                    );